name: Reusable deployment step

on:
  workflow_call:
        
jobs:
  reusable-deployment-job:
    runs-on: windows-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0431404336224C2AA26CEDDB755B239D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_70BDE5FDD149493C9420CD7717961ADD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_95B47F2B739F45639FFCA87EF0187C22 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'appsvcnm1'
          slot-name: 'production'
          package: .
          
